### ISSUE TITLE
Not working for new directories (blocker)

### ISSUE THREAD

**Issue by 304NotModified** [azraelrabbit/AZ.FolderSystemWatcher#1]
Thanks for this library!

Unfortunately it's not sending events when creating new directories. 

None of the events is triggered. 

tested on Win10 x64

**Comment by azraelrabbit** [comment]
sorry , i did not look at this project  for a long time..
and i 'll test and reolve this  soon.

**Comment by azraelrabbit** [comment]
i had test this issue to creating new directory with right click  , i can't fire this issue. and the new version was  pushed .
please try it again .
post reply if any question.
